apiVersion: v1
kind: Service
metadata:
  name: hello-react-service
spec:
  type: NodePort
  selector:
    app: hello-react
  ports:
    - port: 80
      targetPort: 3000
      # nodePort: 30007